name: Python Package using Conda

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: synth
          environment-file: env.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list