name: Unit Tests

on: [push]

jobs:
  unittest:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: synth
          environment-file: env.yml
          auto-activate-base: false
      - run: make
      - run: conda info
      - run: python -m unittest
