name: Unit Tests

on: [push]

jobs:
  unittest:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: zsh {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: synth
          environment-file: env.yml
      - run: make
      - run: conda info
      - run: python -m unittest test.TestOscillator

  linting:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-black: true